apiVersion: v1
kind: Secret
metadata:
    name: secret-postgres-db
type: Opaque
stringData:
    db_url: "jdbc:postgresql://{{DB_URL}}:{{DB_PORT}}/{{DB_NAME}}"
    db_user: {{DB_USER}}
    db_password: {{DB_PASSWORD}}
    db_driver: "org.postgresql.Driver"
    db_dialect: "org.hibernate.dialect.PostgreSQLDialect"